version: '3.8'

services:
  db:
    container_name: appmandb
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_DB: appman
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7436:5432